[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#454545"
blue = "#515FFF"
cyan = "#00FFEC"
green = "#21FF00"
magenta = "#DA00FF"
red = "#FF0000"
white = "#FFFFFF"
yellow = "#FEFF00"

[colors.cursor]
cursor = "#FFFFFF"
text = "#d8d8d8"

[colors.normal]
black = "#000000"
blue = "#0011D1"
cyan = "#00E5D4"
green = "#00cc00"
magenta = "#9500D3"
red = "#C50000"
white = "#ABABAB"
yellow = "#DDE400"

[colors.primary]
background = "#101010"
foreground = "#FFFFFF"

[cursor]
style = "block"
thickness = 0.1
unfocused_hollow = true

[font]
size = 12

[font.bold]
family = "jetbrainsmono"
style = "ExtraBold"

[font.italic]
family = "jetbrainsmono"
style = "light italic"

[font.normal]
family = "jetbrainsmono"
style = "Regular"

[scrolling]
history = 200
multiplier = 2

[window]
opacity = 0.85

[window.padding]
x = 3
y = 3
[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "PageUp"
mods = "Control"
[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "PageDown"
mods = "Control"
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"
